### ISSUE TITLE
Crash with Better Builder's Wands

### ISSUE THREAD

**Issue by magcicada** [vladmarica/energy-meters#12]
When I hold a wand of [Better Builder's Wands](https://www.curseforge.com/minecraft/mc-mods/better-builders-wands) and look at the Energy Meter,the game crashed directly,I don't know what happend.All wands of Better Builder's Wands will crash as the said,it's very strange.
This is [CR](https://paste.ubuntu.com/p/9HxtHbkrG6/)

**Comment by vladmarica** [comment]
Thank you for the bug report. The interaction has been resolved and the fix will be included in the next update.
