### ISSUE TITLE
energy meters seem to have problems reading energy

### ISSUE THREAD

**Issue by xemnes** [vladmarica/energy-meters#18]
not sure why or how, nor can i properly explain whats going on, but over about 10 seconds, the meter will stop reading energy and will flip between 0 and 0.1 forever, its very odd
heres a video: https://gfycat.com/RemarkableZealousCrow

it also goes wild sometimes when trying to get it to update: https://gfycat.com/ExemplaryAridBlackbird

**Comment by vladmarica** [comment]
What version of Energy Meters are you using?

**Comment by xemnes** [comment]
oh um, it turns out i dont think its a bug at all. im just reading it wrong. it only displays energy that needs to flow through it, not the total energy being generated from the source. so if machines are idle, it will do the 0 - 0.1 flip thing because the enderio machines also have an energy leak system. i forgot to close this due to said discovery.
