### ISSUE TITLE
Support the IC2 classic profile

### ISSUE THREAD

**Issue by vladmarica** [vladmarica/energy-meters#8]
Looks like the recipe for the IC2 energy meter doesn't work with the classic profile since Iron Plates don't exist in it. In the case of the IC2 classic profile being used, the meter recipe should use Refined Iron instead.

**Comment by Trinsdar** [comment]
could you make that check check for either ic2 classic or the classic profile? IC2 classic has a dummy mod with the modid 'ic2-classic-spmod`. although one thing I just realized is ic2 classic item ids are different from ic2 experimental item ids, so you might have to do add a constants.json sorta like this mod does:
https://github.com/nekosune/modularforcefieldsystem/blob/1.12/src/main/resources/assets/modularforcefieldsystem/recipes/_constants.json#L83
